---
- name: Setup SGX-Driver and SGX
  hosts: sgx-nodes
  tasks:
  - name: Create base directory
    file:
      path: "{{ base_path }}"
      state: directory
      owner: "{{ user }}"
      recurse: yes
    become: true

  - name: Install dependencies
    action: apt pkg="{{ item }}" state=installed
    with_items:
       - build-essential
       - ocaml
       - automake
       - autoconf
       - libtool
       - wget
       - python2.7
       - libssl-dev
       - libcurl4-openssl-dev
       - protobuf-compiler
       - libprotobuf-dev
       - git
    become: true

  - name: Set python to python 2.7
    alternatives:
      name: python
      link: /usr/bin/python
      path: /usr/bin/python2.7
      priority: 10  
    become: true
  
  - name: clone SGX-Driver
    git: 
      repo: https://github.com/01org/linux-sgx-driver.git
      dest: "{{ base_path }}/linux-sgx-driver/"
      force: yes
 
  - name: Copy script Driver
    copy:
      src: install-driver.sh
      dest: "{{ base_path }}/linux-sgx-driver/"
      mode: 0777

  - name: install SGX-Driver
    shell: ./install-driver.sh
    args:
      chdir: "{{ base_path }}/linux-sgx-driver/"

  - name: clone Intel SGX SDK and PSW
    git:
      repo: https://github.com/01org/linux-sgx.git
      dest: "{{ base_path }}/linux-sgx/"
      force: yes

  - name: Copy script SDK
    copy:
      src: install-sgx.sh
      dest: "{{ base_path }}/linux-sgx/"
      mode: 0777

  - name: install SGX SDK and PSW
    shell: ./install-sgx.sh {{ base_path }}/{{ sdk_path }}
    args:
      chdir: "{{ base_path }}/linux-sgx/"
  
  - name: Prep for git-lfs
    shell: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
 
  - name: Install git-lfs 
    apt:
       name: git-lfs
       state: present 
    
  - name: git lfs install
    shell: git lfs install

  - name: Setup Minotaur
    git:
      repo: https://github.com/MBtech/Minotaur.git
      dest: "{{ base_path }}/Minotaur"

  - name: Solve dependencies of Minotaur
    shell: ./setup.sh
    args:
      chdir: "{{ base_path }}/Minotaur/"
  
        
